name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build App
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o notely
  